version: '3'
services:
  borderlessHQ_service:
    build: .
    ports:
      - "9091:9091"
    depends_on:
      - mongo
      - nats

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  nats:
    image: nats
    ports:
      - "4222:4222"
